config/routes.rb
Rails.application.routes.draw do
  # get 'reasons/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root 'estimates#index'

  resources :estimates do
    resources :reasons
  end
  resources :products
  resources :customers


  get 'product/search' => 'products#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  validates :deadline, presence: true
  validates :discount, length: { maximum: 6 }

  belongs_to :user
  has_many :reasons, dependent: :destroy
  belongs_to :customer
  has_many :estimate_products, dependent: :destroy
  has_many :products, through: :estimate_products
  accepts_nested_attributes_for :estimate_products, allow_destroy: true

  validate :deadline_cannot_be_in_the_past
  validate :discount_check


  def deadline_cannot_be_in_the_past
    errors.add(:納期, "は今日以降を選択してください") if deadline.present? && deadline.past?
  end

  def discount_check
    errors.add(:値引額, "確認してください！！") unless discount < EstimateProduct.sum_prices(estimate_products)
  end
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :setup_estimate_product!, only: [:add_product, :update_product, :delete_product]
  before_action :authenticate_user!, only: [:index, :new, :edit, :update, :destroy]
  before_action :set_estimate, only: [:edit, :update, :destroy]

  def index
    @estimates = current_user.estimates.page(params[:page]).per(5)
    @customers
  end

  def new
    @estimate = Estimate.new
    @products = Product.all
    @estimate.estimate_products.build
  end

  def create
    @estimate = current_user.estimates.build(estimate_params)
    if @estimate.save
      redirect_to estimates_path, notice: "見積書を作成しました！"
    else
      render :new
    end
  end

  def show
    @estimate = current_user.estimates.find(params[:id])
    @products = @estimate.products
    @reasons = @estimate.reasons
    @reason = @estimate.reasons.build
  end

  def edit
    @estimate = current_user.estimates.find(params[:id])
  end

  def update
    @estimate = current_user.estimates.find(params[:id])
    if @estimate.update(estimate_params)
      redirect_to estimates_path, notice: "見積書編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @estimate.destroy
    redirect_to estimates_path, notice:"見積書を削除しました！"
  end


  private

  def estimate_params
    params.require(:estimate).permit(:total_price, :discount, :quantity, :customer_id,
                                     :deadline,{ product_ids: [] }, :product_name, :quantity,
                                     [estimate_products_attributes:[:id, :estimate_id, :product_id, :quantity, :_destroy]]
                                     ).merge(user_id: current_user.id)
  end

  def total(unit_price, quantity)
    unit_price.find * @estimate_product.quantity
  end

  def set_estimate
    @estimate = Estimate.find(params[:id])
  end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_estimate_product_fields.html.erb
<div class='nested-fields'>
    <div class="field">
      <%= f.label :product, "製品名" %>
      <%= f.collection_select :product_id, Product.all, :id, :name, include_blank: "選択して下さい" %>
      <%= f.label :quantity, '×' %>
      <%= f.number_field :quantity %>
    <%= link_to_remove_association '削除', f, id: 'remove-btn' %>
    </div>
  </div>

app/views/estimates/_form.html.erb
<%= form_with(model: @estimate, local: true ) do |f| %>
  <% if @estimate.errors.any? %>
    <div id="error_explanation">
      <h2><%= @estimate.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @estimate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<center>
  <div class="customer_name">
    <%= f.label :customer %>
    <%= f.collection_select :customer_id, Customer.all, :id, :name, include_blank: "選択して下さい" %>
  </div>



  <div class="deadline">
    <%= f.label :deadline, "納期" %>
    <%= raw sprintf(
    f.date_select(
    :deadline,
    use_month_numbers: true,
    start_year:        2020,
    end_year:          (Time.now.year + 20),
    default:           Date.new(2020, 1, 1),
    date_separator:    '%s'), # 年月日区切りをそれぞれ指定
    '年 ', '月 ') + '日'
    %>
  </div>

  <div class="discount">
    <%= f.label :discount, "値引額" %>
    <%= f.text_field :discount %>
  </div>

<%= f.fields_for :estimate_products do |ep| %>
   <%= render 'estimate_product_fields', f: ep %>
    <div class='links'>
      <%= link_to_add_association '＋別の製品を追加', f, :estimate_products %>
    </div>
<% end %>

  <div>
    <%= f.submit %>
  </div>
<% end %>

  <div>
    <%= link_to '見積書一覧画面に戻る', estimates_path %>
  </div>
</center>

app/views/estimates/edit.html.erb
<h1>見積書編集ページ</h1>
 <%= render 'form' %>

app/views/estimates/index.html.erb
<h3>見積書一覧</h3>
<h3>担当者:<%= current_user.name %></h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>見積書ID</th>
      <th>顧客名</th>
    </tr>
  </thead>
  <tbody>
    <% @estimates.each do |estimate| %>
    <tr>
      <td><%= estimate.id %></td>
      <td><%= estimate.customer.name %></td>
      <td><%= link_to '見積書詳細', estimate_path(estimate), class: "btn btn-outline-primary" %></td>
      <td><%= link_to "見積書編集", edit_estimate_path(estimate), class: "btn btn-outline-warning", data: { confirm: '本当に編集していいですか？' } %></td>
      <td><%= link_to '見積書削除', estimate_path(estimate), class: "btn btn-outline-danger", method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @estimates %>

app/views/estimates/new.html.erb
<h1>見積書作成ページ</h1>
 <%= render 'form' %>

app/views/estimates/show.html.erb
<center>
<table>
  <h3><%= @estimate.customer.name %> 御中</h3>
</table>

<table>
  <tr>
    <th>製品名</th>
    <th>単価</th>
    <th>数量</th>
  </tr>
  </table>
<table>

<% sum = 0 %>
<% @estimate.products.each do | pro | %>
<tr>
  <td><%= pro.name %></td>
  <td><%= p = pro.unit_price %></td>
  <td>
    <%= q = @estimate.estimate_products.find_by(product_id: pro.id).quantity %>
  </td>
  <td>
    <%= p * q %>
  </td>
</tr>
<% sum += p * q %>
<% end %>
</table>


<table>
<p>納期: <%= @estimate.deadline %></p>
<p class="text-danger">値引: <%= @estimate.discount %></p>
<% if @estimate.discount == nil %>
  <p>金額: <%= sum %></p>
  <p>税込: <%= ((sum * 1.1).round(2)).ceil %></p>
<% else %>
  <p>金額: <%= sum-@estimate.discount %></p>
  <p>税込: <%= ((sum-@estimate.discount) * 1.1).round(2).ceil %></p>
<% end %>
</table>

  <p id="notice"><%= notice %></p>
  <p>値引き理由</p>
  <!-- このreasons_areaというHTMLのidを取得して、そのdivの部分だけを更新する -->
  <div id="reasons_area">
    <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
    <%= render partial: 'reasons/index', locals: { reasons: @reasons, estimate: @estimate } %>
  </div>
  <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
  <%= render partial: 'reasons/form', locals: { reason: @reason, estimate: @estimate } %>
  <%= link_to '見積書編集', edit_estimate_path(@estimate), class: "btn btn-outline-warning" %>
<div>
  <%= link_to '見積書一覧画面に戻る', estimates_path %>
</div>
</center>