config/routes.rb
Rails.application.routes.draw do
  # get 'reasons/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root 'estimates#index'

  resources :estimates do
    resources :reasons
  end
  resources :products
  resources :customers


  get 'product/search' => 'products#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reason.rb
class Reason < ApplicationRecord
  validates :content, presence: true
  belongs_to :estimate
  belongs_to :user
end

app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
  before_action :set_estimate, only: [:create, :edit, :update]
  def create
   @estimate = Estimate.find(params[:estimate_id])
   @reason = @estimate.reasons.build(reason_params)
    respond_to do |format|
      if @reason.save
        format.js { render :index }
      else
        format.html { redirect_to estimate_path(@estimate), notice: '理由を記入してください！' }
      end
    end
  end

  def edit
    @reason = @estimate.reasons.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = '理由の編集中'
      format.js { render :edit }
    end
  end

  def update
    @reason = @estimate.reasons.find(params[:id])
    respond_to do |format|
      if @reason.update(reason_params)
        flash.now[:notice] = '理由が編集されました'
        format.js { render :index }
      else
        flash.now[:notice] = '理由の編集に失敗しました'
        format.js { render :edit_error }
      end
    end
  end

  def destroy
    @reason = Reason.find(params[:id])
    @reason.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end

 private

  def reason_params
    params.require(:reason).permit(:estimate_id, :content, :user_id)
  end

  def set_estimate
    @estimate = Estimate.find(params[:estimate_id])
  end
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/views/reasons/_edit.html.erb
<%= form_with(model: [estimate, reason]) do |form| %>
  <% if reason.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reason.errors.count, "error") %> prohibited this reason from being saved:</h2>
      <ul>
      <% reason.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content, id: "reason_content_#{estimate.id}" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reasons/_form.html.erb
<!-- この記述がestimateのshow画面に表示されるコメント入力欄になります -->
<%= form_with(model: [estimate, reason]) do |form| %>
  <% if reason.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reason.errors.count, "error") %> prohibited this reason from being saved:</h2>
      <ul>
      <% reason.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content %>
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reasons/_index.html.erb
<ul>
  <% reasons.each do |reason| %>
    <% if reason.id.present? %>
      <li>
        <div class="reason-content" id ="this_reason_<%= reason.id %>"></div>
        <p><%= reason.content %></p>
        <p><%= link_to "コメント編集", edit_estimate_reason_path(estimate, reason), remote: true %></p>
        <p><%= link_to "コメント削除", estimate_reason_path(reason.estimate_id, reason.id), method: :delete, remote: true,
                                     data: { confirm: "本当に削除しますか?"}, class: "text-danger" %></p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/reasons/create.html.erb
<h1>Reasons#create</h1>
<p>Find me in app/views/reasons/create.html.erb</p>

app/views/reasons/edit.js.erb
$("#this_reason_<%= @reason.id %>").replaceWith("<%= j render 'reasons/edit', estimate: @estimate, reason: @reason %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/reasons/index.js.erb
$("#reasons_area").html("<%= j(render 'reasons/index', { reasons: @reason.estimate.reasons, estimate: @reason.estimate }) %>")
$("textarea").val('')
$("#notice").html("<%= j flash[:notice] %>");