config/routes.rb
Rails.application.routes.draw do
  # get 'reasons/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root 'estimates#index'

  resources :estimates do
    resources :reasons
  end
  resources :products
  resources :customers


  get 'product/search' => 'products#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grafoure</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% if current_user.try(:admin?) %>
    <% if user_signed_in? %>
      <%= link_to "見積書作成", new_estimate_path, class: "btn btn-primary btn-sm" %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-sm" %>
    <% end %>
  <%= link_to '管理者画面', rails_admin_path, class: "btn btn-dark btn-sm" %>
  <% else %>
    <% if user_signed_in? %>
      <%= link_to "見積書作成", new_estimate_path, class: "btn btn-primary btn-sm" %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-sm" %>
    <% end %>
  <% end %>

  <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>
  <%= yield %>
</body>
</html>
<!-- link_to "ログイン", new_user_session_path, class: "btn btn-primary btn-sm" -->